{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ include "backend.namespace" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
{{- end }}
