{{- $db := .Values.global.database -}}
{{- if not $db.existingDatabase }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.headlessService" . }}
  namespace: {{ include "database.namespace" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ $db.service.port }}
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  namespace: {{ include "database.namespace" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ $db.service.type }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ $db.service.port }}
      targetPort: postgres
{{- end }}
