{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.secretName" . }}
  namespace: {{ include "database.namespace" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKeys.usernameKey }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.secretKeys.passwordKey }}: {{ .Values.auth.password | quote }}
  {{ .Values.auth.secretKeys.databaseKey }}: {{ .Values.auth.database | quote }}
{{- end }}
