name: Lint Chart

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4

      - name: Lint chart
        run: helm lint ./charts/cloudcost --strict

      - name: Template chart
        run: helm template cloudcost ./charts/cloudcost
